---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo
  labels:
    app: silly-demo
    component: web
spec:
  selector:
    matchLabels:
      app: silly-demo
      component: web
  template:
    metadata:
      labels:
        app: silly-demo
        component: web
    spec:
      containers:
      - name: silly-demo
        image: vfarcic/silly-demo:1.0.4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: db-auth
          mountPath: /mnt/secrets-store
          readOnly: true
      serviceAccountName: silly-demo
      volumes:
      - name: db-auth
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: db-auth
